{{- if .Values.dapp.mnemonic.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.fullname" . }}-mnemonic
  labels: {{- include "validator.labels" . | nindent 4 }}
type: Opaque
data:
  MNEMONIC: {{ .Values.dapp.mnemonic.value | b64enc }}
{{- end }}
