# (c) Cartesi and individual authors (see AUTHORS)
# SPDX-License-Identifier: Apache-2.0 (see LICENSE)

apiVersion: v2
name: rollups-validator-node
description: A Helm chart for a Cartesi Rollups Validator Node
maintainers:
  - name: EndersonMaia
    email: endersonmaia@gmail.com
    url: https://github.com/endersonmaia
  - name: oap75
    email: omid.asadpoor36@gmail.com
    url: https://github.com/oap75

type: application
version: 1.0.0

dependencies:
  - name: redis
    version: 17.3.11
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
