apiVersion: v2
name: rollups-validator-node
description: A Helm chart for a Cartesi Rollups Validator Node
maintainers:
  - name: endersonmaia
  - name: oap75

type: application
version: 0.5.0
appVersion: "0.9.1"

dependencies:
  - name: redis
    version: 17.3.11
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
